ONTOLOGY_NAME: magnetic-materials
ONTOLOGY_PREFIX: magmo
ONTOLOGY_IRI: https://w3id.org/emmo/domain/magnetic-materials
GITHUB_REPOSITORY: emmo-repo/domain-magnetic-materials
BUILD_DIR: build
GIT_REPOSITORY: emmo-repo/domain-magnetic-materials
GIT_BASE_URL: github.com
REFERENCE_SUBSECTIONS: all
REFERENCE_IMPORTED: 'false'
REFERENCE_RECURSIVE: 'true'
REFERENCE_IRI_REGEX: None#

# Optional settings for `ontokit docs` reference indices.
# Select subsections for the primary reference index. Default is "all".
# REFERENCE_SUBSECTIONS: all
# Example subset:
# REFERENCE_SUBSECTIONS: classes,annotation_properties,data_properties,object_properties,individuals
#
# REFERENCE_IMPORTED: false
# REFERENCE_RECURSIVE: true
# This regex is used to filter which IRIs are included in the primary reference index. Default is the ontology IRI.
# REFERENCE_IRI_REGEX: https://example.com/myonto#
#
# Optional: additional reference indices for `ontokit docs`.
# REFERENCE_INDICES:
#   - ontology_file: build/other-ontology.ttl
#     title: Other Ontology Reference
#     docfile: other-reference.rst
#     iri_regex: https://example.org/other
#     imported: false
#     recursive: false
#     subsections: all
