[workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
name = "domain-magnetic-materials"
version = "0.0.6"
authors = [
  "Martin Dobiasch",
  "Hans Fangohr",
  "Samuel Holt",
  "Wilfried Hortschitz",
  "Martin Lang",
  "Swapneel Amit Pathak",
  "Andrea Petrocchi",
  "Thomas Schrefl",
]
description = "Magnetic Materials Domain Ontology (MagMO)."

[tasks]
build = {cmd="python src/build_ontology.py", description="Build ontology"}
reason = "ontoconvert magnetic-materials.ttl magnetic-materials.ttl --reasoner --infer --namespace emmo:https://w3id.org/emmo#"
check = "emmocheck magnetic-materials.ttl"
all = { depends-on = ["build", "reason", "check"] } # run all steps subsequently
prepare-test = "rm -rf build && mkdir build && cp contributors.ttl catalog-v001.xml magnetic-materials-dependencies.ttl build"
test-build-ontology = {cmd = "python ../src/build_ontology.py && ontoconvert magnetic-materials.ttl ../generated.ttl --reasoner --infer --namespace emmo:https://w3id.org/emmo# && emmocheck ../generated.ttl", cwd = "build", depends-on=["prepare-test"]}
test = {cmd = "pytest -vv", depends-on=["prepare-test", "test-build-ontology"]}

[dependencies]
emmontopy = ">=0.11.4"
python = ">3.11"
openjdk = ">=25.0.2,<26"
ipython = ">=9.10.0,<10"
sphinx = ">=9.1.0,<10"
pytest = ">=9"

[pypi-dependencies]
