
abstract=An EMMO-based domain-ontology for magnetic materials. Created within the EU project MaMMoS. Grant number 101135546 (HORIZON-CL4-2023-DIGITAL-EMERGING-01). The Magnetic Materials Ontology is released under the Creative Commons Attribution 4.0 International license (CC BY 4.0).
ontologyTitle=Magnetic Materials Ontology (MagMO)
ontologyPrefix=MagMO
ontologyNamespaceURI=https://w3id.org/emmo/domain/magnetic-materials
ontologyName=Magnetic Materials Ontology (MagMO)
thisVersionURI=https://w3id.org/emmo/domain/0.0.5/magnetic-materials
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=0.0.5
licenseURI=http://purl.org/NET/rdflicense/cc-by4.0
licenseName=Creative Commons CC-BY
licenseIconURL=null
citeAs=https://w3id.org/emmo/domain/magnetic-materials#SantaPile, https://w3id.org/emmo/domain/magnetic-materials#ThomasSchrefl, https://w3id.org/emmo/domain/magnetic-materials#WilfriedHortschitz. Magnetic Materials Ontology (MagMO). Revision: 0.0.5. Retrieved from: https://w3id.org/emmo/domain/0.0.5/magnetic-materials
DOI=
status=unstable
logo=
description=Contacts:
Wilfried Hortschitz
DISS-UWK
email: wilfried.hortschitz@donau-uni.ac.at

introduction=
backwardsCompatibleWith=
publisher=https://mammos-project.github.io
publisherURI=https://mammos-project.github.io
publisherInstitution=
publisherInstitutionURI=
authors=https://w3id.org/emmo/domain/magnetic-materials#SantaPile;https://w3id.org/emmo/domain/magnetic-materials#ThomasSchrefl;https://w3id.org/emmo/domain/magnetic-materials#WilfriedHortschitz
authorsURI=https://w3id.org/emmo/domain/magnetic-materials#SantaPile;https://w3id.org/emmo/domain/magnetic-materials#ThomasSchrefl;https://w3id.org/emmo/domain/magnetic-materials#WilfriedHortschitz
authorsInstitution=;;
authorsInstitutionURI=;;
contributors=https://w3id.org/emmo/domain/magnetic-materials#AndreaPetrocchi;https://w3id.org/emmo/domain/magnetic-materials#HansFangohr;https://w3id.org/emmo/domain/magnetic-materials#JonasWinkler;https://w3id.org/emmo/domain/magnetic-materials#MartinLang;https://w3id.org/emmo/domain/magnetic-materials#SamHolt;https://w3id.org/emmo/domain/magnetic-materials#SwapneelAmitPathak;https://w3id.org/emmo/domain/magnetic-materials#WilliamRigaut
contributorsURI=https://w3id.org/emmo/domain/magnetic-materials#AndreaPetrocchi;https://w3id.org/emmo/domain/magnetic-materials#HansFangohr;https://w3id.org/emmo/domain/magnetic-materials#JonasWinkler;https://w3id.org/emmo/domain/magnetic-materials#MartinLang;https://w3id.org/emmo/domain/magnetic-materials#SamHolt;https://w3id.org/emmo/domain/magnetic-materials#SwapneelAmitPathak;https://w3id.org/emmo/domain/magnetic-materials#WilliamRigaut
contributorsInstitution=;;;;;;
contributorsInstitutionURI=;;;;;;
importedOntologyNames=contributors
importedOntologyURIs=https://w3id.org/emmo/domain/magnetic-materials/contributors
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
