
abstract=An EMMO-based domain-ontology for magnetic materials. Created within the EU project MaMMoS. Grant number 101135546 (HORIZON-CL4-2023-DIGITAL-EMERGING-01). The Magnetic Materials Ontology is released under the Creative Commons Attribution 4.0 International license (CC BY 4.0).
ontologyTitle=Magnetic Materials Ontology (MagMO)
ontologyPrefix=magmo
ontologyNamespaceURI=https://w3id.org/emmo/domain/magnetic-materials
ontologyName=Magnetic Materials Ontology (MagMO)
thisVersionURI=https://w3id.org/emmo/domain/0.0.6/magnetic-materials
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=0.0.6
licenseURI=http://purl.org/NET/rdflicense/cc-by4.0
licenseName=Creative Commons CC-BY
licenseIconURL=null
citeAs=https://orcid.org/0000-0001-7854-847X, https://orcid.org/0000-0002-0871-0520, https://orcid.org/0000-0003-2950-642X. Magnetic Materials Ontology (MagMO). Revision: 0.0.6. Retrieved from: https://w3id.org/emmo/domain/0.0.6/magnetic-materials
DOI=
status=http://purl.org/ontology/bibo/term_status/unstable
logo=
description=Contacts:
Wilfried Hortschitz
DISS-UWK
email: wilfried.hortschitz@donau-uni.ac.at

introduction=
backwardsCompatibleWith=
publisher=https://mammos-project.github.io
publisherURI=https://mammos-project.github.io
publisherInstitution=
publisherInstitutionURI=
authors=https://orcid.org/0000-0001-7854-847X;https://orcid.org/0000-0002-0871-0520;https://orcid.org/0000-0003-2950-642X
authorsURI=https://orcid.org/0000-0001-7854-847X;https://orcid.org/0000-0002-0871-0520;https://orcid.org/0000-0003-2950-642X
authorsInstitution=;;
authorsInstitutionURI=;;
contributors=https://orcid.org/0000-0001-5494-7193;https://orcid.org/0000-0001-7104-7867;https://orcid.org/0000-0003-3323-8958;https://orcid.org/0000-0003-3840-955X;https://orcid.org/0009-0000-7815-5916;https://orcid.org/0009-0000-9775-7955;https://orcid.org/0009-0005-1867-6732
contributorsURI=https://orcid.org/0000-0001-5494-7193;https://orcid.org/0000-0001-7104-7867;https://orcid.org/0000-0003-3323-8958;https://orcid.org/0000-0003-3840-955X;https://orcid.org/0009-0000-7815-5916;https://orcid.org/0009-0000-9775-7955;https://orcid.org/0009-0005-1867-6732
contributorsInstitution=;;;;;;
contributorsInstitutionURI=;;;;;;
importedOntologyNames=contributors
importedOntologyURIs=https://w3id.org/emmo/domain/magnetic-materials/contributors
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=
fundingGrants=
funders=
